### ISSUE TITLE
Ideas for new functionality

### ISSUE THREAD

**Issue by NaamloosDT** [NaamloosDT/ModCore#10]
I've taken a look at some more popular moderation bots and hand picked a couple of functions that would be nice for modcore. (and thought up a couple)

- [x] Temporary bans
- [x] Global warnings (moderators from other guilds can see whether users have done more bad things)
- [x] Temporary mutes (mutes are at the moment permanent untill you unmute)
- [x] Leave server (for those who want to make the bot leave on its own)
- [x] Temporary pins (unpin after specific date/time)
- [x] Reminders (remind me to ban this guy after 2 hours :^)  )
- [x] Clean bot's own commands (basically a shortcut to purge, or perhaps with user commands included)
- [x] Automated Kicks/Bans (after certain amount of warnings/strikes)
- [x] Scheduled Pins
- [x] Server warnings (these trigger the auto-kick/ban)
- [x] Tag system
- [x] Prune by regex
 
These are just proposals. Feel free to add anything c:

**Comment by uwx** [comment]
haha i can tick the boxes and that changes the markdown

**Comment by NaamloosDT** [comment]
Yup. And I just finished one of them c:

**Comment by armaa** [comment]
Ive got a few ideas
Scheduled kicks/bans - Maybe not that much useful, but can be fancy/fun i guess
Automated kicks/bans - After 3/5/n strikes an user gets for bad behaviour/saying specific phrases or words/an admin assigns one, the user gets kicked/banned for some time
Strikes - As mentioned above, an admin could have an option to assign strikes to users manually for whatever 'wrong' they do

**Comment by NaamloosDT** [comment]
Interesting ideas, I'll add them to the checklist. Thanks!

**Comment by NaamloosDT** [comment]
However I think strikes are basically the same thing as warnings.

**Comment by armaa** [comment]
I was thinking more or server/guild only warnings (strikes), different from global ones. Imagine if user had 5 global warnings and mod core is on that server, he would be kicked right as he joins, right?

**Comment by NaamloosDT** [comment]
Good point

**Comment by NaamloosDT** [comment]
Updated checklist.

**Comment by NaamloosDT** [comment]
Oops

**Comment by NaamloosDT** [comment]
Removed Scheduled kicks/bans/mutes (unneccesary to do those after a time period)

**Comment by armaa** [comment]
Since i got the notification, might as well post the ideas
What about roles/emojis prune/clean up? Like if an emoji wasnt used in a few weeks or maybe a month, calling the, lets call it `!pruneemoji`, command would remove them from the guild
Similar for roles, if there are some roles which arent assigned to anyone or anything along those lines, calling a similar command would remove those

**Comment by NaamloosDT** [comment]
Could do that, though that doesn't seem like something a lot of people would use imo. Emoji usage isn't that huge anyway usually

**Comment by armaa** [comment]
Thats true about emojis, thats why maybe set a limit to delete ones not used for 6+ months or maybe even more, depending on your feel or maybe make the limit set by the admin/mod?
Maybe similar thing for roles too, even tho roles are usually *carefully* made and taken care of, but either way just call the whole thing `spring cleaning` :^)

**Comment by NaamloosDT** [comment]
Added prune by regex to the list. It a rather advanced feature for moderators that wanna get their hands dirty ;)

**Comment by uwx** [comment]
done and done.avi

**Comment by armaa** [comment]
Maybe make an active prune, in a way that if some user mentions a word/phrase thats banned in the discord (which could maybe be set by admin or whoever) that it auto deletes the message or quotes the message with that word/phrase substituted with stars or some maybe some other funny word/phrase
Never 4get overwatch `gg wp` :^)

**Comment by jcryer** [comment]
#30 
Something something Global Bans something something

**Comment by NaamloosDT** [comment]
Everything is implemented. Closing this issue.
