### ISSUE TITLE
Issue with timers

### ISSUE THREAD

**Issue by NaamloosDT** [NaamloosDT/ModCore#68]
Sometimes timers break, and keep resetting themselves. This is to be investigated ;^)

**Cause:**
unknown

**What happens:**
When setting a reminder, you won't get a confirmation message, yet the timer will be saved to the database. Once the timer is hit, it will just reset itself. This issue would just pop up randomly for (seemingly) no reason.

Currently it seems like a rebbot or cleaning the database table fixes it, yet we need a permanent full-on fix for this

**Comment by Emzi0767** [comment]
Cause: someone touched and broke my code.

Likely caused by someone improperly handling expiration, throwing an exception that gets swallowed.

**Comment by NaamloosDT** [comment]
Next mystery: who did? what part?

tune in next time for a new episode of scooby and the gang!

**Comment by jcryer** [comment]
~~Wasn't me~~

**Comment by NaamloosDT** [comment]
*theme song starts playing*

**Comment by NaamloosDT** [comment]
Found the cause of the issue: update command.
If the bot reboots via update it breaks.

**Comment by NaamloosDT** [comment]
Closing the issue as it seems to be resolved. Will re-open if issue returns somehow.

**Comment by NaamloosDT** [comment]
3ab3a78686256de55b1e60162639ac243f7e3e00
